BlogEpam/WebBlog/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBlog.CR;
using WebBlog.Models.Entity;
using WebBlog.Services;

namespace WebBlog.Web.Controllers
{
    public class GuestController : Controller
    {
        ICreatorOfInctances creatorOfInctances;
        ProviderCommentQuery commentQuery;

        public GuestController(ICreatorOfInctances creatorOfInctances)
        {
            this.creatorOfInctances = creatorOfInctances;
            commentQuery = new ProviderCommentQuery(creatorOfInctances.GetInstanceCommentQuery(),
                creatorOfInctances.GetInstanceCommentRepository(),creatorOfInctances.GetInstanceUserQuery(),
                creatorOfInctances.GetInstanceUserRepository());
        }
        // GET: GuestPage

        [HttpGet]
        public ActionResult Index()
        {
            var comments = commentQuery.GetCommentsByType("GuestPage").ToList();  
            
            return View(comments);
        }

        [HttpPost]
        public ActionResult Index(string email, string name, DateTime date, string text)
        {
            commentQuery.AddCommentForGuestPage(email, name, date, text);
            return Redirect("/Guest/Index");
        }
    }
}

BlogEpam/WebBlog/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBlog.Services;
using WebBlog.CR;
using WebBlog.Models.Entity;

namespace WebBlog.Web.Controllers
{
    public class MainController : Controller
    {
        ICreatorOfInctances creatorOfInctances;
        ProviderArticleQuery articleQuery;

        public MainController(ICreatorOfInctances creatorOfInctances)
        {
            this.creatorOfInctances = creatorOfInctances;
            articleQuery = new ProviderArticleQuery(creatorOfInctances.GetInstanceArticleQuery());
        }       

        public ActionResult Index()
        {    
            var allArticles = articleQuery.GetAllArticles().ToList();
                 
            return View(allArticles);
        }

        public ActionResult Article()
        {
            var article = articleQuery.GetArticle(new Guid(Request.Params["id"]));           
            return View(article);
        }
    }
}

BlogEpam/WebBlog/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBlog.CR;
using WebBlog.Models.EntityForViews;
using WebBlog.Services;

namespace WebBlog.Web.Controllers
{
    public class QuestionnaireController : Controller
    {
        ICreatorOfInctances creatorOfInctances;
        ProviderQuestionnaireQuery commentQuery;

        public QuestionnaireController(ICreatorOfInctances creatorOfInctances)
        {
            this.creatorOfInctances = creatorOfInctances;
            commentQuery = new ProviderQuestionnaireQuery(creatorOfInctances.GetInstanceQuestionnaireQuery());
        }

        public ActionResult Index()
        {
            var questionnaire = commentQuery.GetQuestionnaireByTitle("Оцените пожалуйста наш сайт");
            return View(questionnaire);
        }
        [HttpPost]
        public ActionResult QuestionnaireResult()
        {
            var questionnaireResult = new QuestionnaireResult(Request.Form,
                creatorOfInctances.GetInstanceQuestionnaireQuery(),
                creatorOfInctances.GetInstanceWebBlogRatingRepository());
            var userMark = questionnaireResult.UserEvaluation();

            var questionnaireEntity = new QuestionnaireEntity { Name = Request.Form["personeName"], Mark = userMark};

            return View(questionnaireEntity);
        }

        public ActionResult GetQuestion()
        {
            return PartialView();
        }
    }
}

BlogEpam/WebBlog/Views/Guest/Index.cshtml
@using WebBlog.Models.Entity;

@model System.Collections.Generic.List<Comment>


<div class="guest-form">
    <form method="post">
        <input type="hidden" value="@DateTime.Now" name="date" />
        <h2>Оставить отзыв</h2>
        <label for="email">Введите ваш email</label>
        <br />
        <input type="text" name="email" placeholder="Email" />
        <br />
        <label for="name">Введите ваше имя</label>
        <br />
        <input type="text" name="name" placeholder="Имя" />
        <br />
        <label for="text">Отзыв</label>
        <br />
        <textarea name="text" placeholder="Текст отзыва"></textarea>
        <br />
        <input type="submit" name="submit" value="Отправить" />
    </form>
</div>

@if (Model.Count() != 0)
{
    <div class="reviers">
        @foreach (var Item in Model)
        {

            <div class="review">
                <p class="review-name">@Item.Users.Name</p>
                <p class="review-date">@Item.Date.ToString()</p>
                <p class="review-text">@Item.Text</p>
            </div>
        }
    </div>
}

BlogEpam/WebBlog/Views/Main/Article.cshtml
@model WebBlog.Models.Entity.Article

@{
    ViewBag.Title = "Article";
}

<div class="article-page">
    <h2>@Model.Title</h2>
    <p>@Model.Date</p>
    <p>@Model.User.Name</p>
    <p>@Model.Text</p>
</div>

BlogEpam/WebBlog/Views/Main/Index.cshtml
@using WebBlog.Models.Entity;

@model System.Collections.Generic.List<Article>

@foreach (var article in Model)
{<div class="article">
        <a href="/Main/Article?id=@article.Id.ToString()">
            <p class="article-title">@article.Title</p>
            <p class="article-date">@article.Date.ToString()</p>
            <p class="article-text">@article.Text</p>
        </a>
    </div>
}

BlogEpam/WebBlog/Views/Questionnaire/GetQuestion.cshtml
@model WebBlog.Models.Entity.QuestionnaireComponents.Question
@using WebBlog.Models.Entity.QuestionnaireComponents

<fieldset>
    <h2 class="question-title">@Model.Title</h2>
    @OutputQuestions(Model.Answer, Model.Title)
</fieldset>


@helper OutputQuestions(ICollection<Answer> answers, string name)
    {
        foreach (var ansver in answers)
        {
            <div class="label-input-wrap">
                @if (Model.Type == "radiobutton")
                {
                    <input type="radio" name="@name" value="@ansver.Id" />
                }
                @if (Model.Type == "checkbox")
                {
                    <input type="checkbox" name="@name" value="@ansver.Id" />
                }
                <label for="name">@ansver.Title</label>
            </div>
        }
}

BlogEpam/WebBlog/Views/Questionnaire/Index.cshtml
@model WebBlog.Models.Entity.QuestionnaireComponents.Questionnaire

<div class="questionnaire-form">
    <h1>Оценка веб-сайта – Оценка работы сайта посетителями</h1>
    <h2>Здравствуйте, потратьте, пожалуйста, несколько минут своего времени на заполнение следующей анкеты.</h2>

    <form method="post" action="/Questionnaire/QuestionnaireResult">
        <input type="hidden" value="@Model.Id" name="questionnaireId" />    
        <label for="personName">Введите ваше имя</label>
        <br />
        <input type="text" name="personName" placeholder="Имя" />
        @foreach (var item in Model.Questions)
    {
        @Html.Partial("GetQuestion", item)
}
        <label for="recomendations">Как на ваш взгляд можно улучшить веб сайт</label>
        <br />
        <textarea name="recomendations" placeholder="Ваши рекомендации"></textarea>
        <br />
        <input type="submit" name="submit" value="Отправить" />
    </form>
</div>

BlogEpam/WebBlog/Views/Questionnaire/QuestionnaireResult.cshtml
@model WebBlog.Models.EntityForViews.QuestionnaireEntity


<div class="questionnaire-result">
    <h2>@Model.Name результат опроса</h2>
    <div class="info">
        <p>Вы оценили Blog @Model.Mark из 100 </p>
        <p>Спасибо за ваш отклик</p>
    </div>
</div>

BlogEpam/WebBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    @*<script src="~/Scripts/JavaScript.js"></script>*@
    @*<script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>*@
    <script src="~/Scripts/jquery.min.js"></script>
    <title>@ViewBag.Title - Blog</title>
</head>
<body>
   
        <header class="clearfix" id="header">
            <a href="~/Main/Index">
                <img class="icon" src="~/Images/Blog.png" alt="icon" />
                <div class="name">Blog</div>
            </a>

        </header>


        <div class="container clearfix">
            <nav>
                <ul>
                    <li>@Html.ActionLink("Главная", "Index", "Main")</li>
                    <li>@Html.ActionLink("Гостевая", "Index", "Guest")</li>
                    <li>@Html.ActionLink("Анкета", "Index", "Questionnaire")</li>
                    
                </ul>
            </nav>

            <section class="content ">
                @RenderBody()
            </section>

        </div>

        <footer>
            <p>&copy; Blog - все права зашищены</p>
        </footer>
  

    <a class="button-top" id="button-top" href="#header"><img src="~/Images/backTop.png" alt="TOP" /></a>
    <script>
        jQuery(function ($) {
            $(".button-top").click(function () {
                var elementClick = $(this).attr("href")
                var destination = $(elementClick).offset().top;
                jQuery("html:not(:animated),body:not(:animated)").animate({ scrollTop: destination }, 800);
                return false;
            });
           
        });
    </script>

</body>
</html>